### ISSUE TITLE
feature request: warn of for loop no-ops

### ISSUE THREAD

**Issue by tbrowder** [drforr/perl6-Perl6-Tidy#2]
I found a trap recently where rakudo gave no warning:

    for 5..2 {
        say $_
    }

The loop is not entered because the range returns zero somehow.  The proper
way to get the desired reverse iteration is to use the sequence operator (three dots):

    for 5...2 {
        say $_
    }

It would be great if someday Perl6::Tidy could catch such an apparent error.

Thanks for creating this project.

**Comment by tbrowder** [comment]
According to @drforr, this more properly a feature of hi planned Perl6::Lint. Closing this until Perl6::Lint is unveiled.

**Comment by drforr** [comment]
Eventually :)
