### ISSUE TITLE
Add support for K&R formatting style.

### ISSUE THREAD

**Issue by faraco** [drforr/perl6-Perl6-Tidy#4]
It would be great if Perl6::Tidy support K&R C commonly used formatting style.

**Comment by drforr** [comment]
I thought that was one of the choices I offered, but it's been a while since I've looked at the code. I basically borrowed Wikipedia's brace styles and assumed that K&R was among the list of alternatives. You can always look at the documentation for more info...

**Comment by faraco** [comment]
Oh my bad. I just learned what 1TBS supposed to mean and how the formatting looks. Both are identical it seems.

**Comment by drforr** [comment]
Heh. I'll add a note in the doco and maybe an alias for K&R - I guess the '&' was what I was most concerned about.

**Comment by drforr** [comment]
I'm also grateful that someone actually recognized this as an omission - it means the code is out there and actually being used, which is wonderful.
