### ISSUE TITLE
zef: No candidates found matching identity: Perl6::Tidy

### ISSUE THREAD

**Issue by cfa** [drforr/perl6-Perl6-Tidy#5]
The readme documents `zef`installation, but it looks like `Perl6::Tidy` isn't registered in the ecosystem:

    ===> Searching for: Perl6::Tidy
    No candidates found matching identity: Perl6::Tidy

If the intent is to document local installation after cloning, perhaps this could be clarified?

**Comment by drforr** [comment]
I was going to say that I wasn't going to put it up until it did something non-trivial, but I remembered both that it does brace rearrangement *and* had someone file a bug against it, which means it's already out in the wild. I'll use the magic of App::Mi6 to push this after I get back from supper.

**Comment by drforr** [comment]
Closed because I pushed it last night to CPAN/ecosystem.
