### ISSUE TITLE
Missing Perl6::Parser dependency declaration

### ISSUE THREAD

**Issue by cfa** [drforr/perl6-Perl6-Tidy#7]
To wit,

    $ zef install Perl6::Tidy
    ===> Searching for: Perl6::Tidy
    ===> Testing: Perl6::Tidy:ver<0.0.1>:auth<github:drforr>
    ===SORRY!===
    Could not find Perl6::Parser at line 122 in [...]

**Comment by drforr** [comment]
Yep. I'll fix it through the GH interface as (even though it's a simple fix) I appear to have uncovered a bug in App::Mi6.

**Comment by drforr** [comment]
Wasn't a bug, was my mishandling of App::Mi6. Pushed to CPAN.
