### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by remorse** [drforr/perl6-Perl6-Tidy#8]
Hi! In the `README.md` file, you have a section which is supposed to demonstrate the different types of indentation styles. They all look the same, and based on the names, are (all) wrong, as they all are just one line.

(Also, could you include an `if ... else` statement, so that the demonstration demonstrates whether it created "cuddled elses"?)

**Comment by drforr** [comment]
Thanks for catching that; I need to learn GH style markdown or something. I'll take a look at it after I get back from supper/movie.

**Comment by drforr** [comment]
Uh, I definitely did *not* make those changes, I think I need to file a bug for App::Mi6 because I'm *positive* I actually used real samples of code there. Not blaming App::Mi6, I just need to figure out what went wrong.

**Comment by drforr** [comment]
Released v0.0.3 with the updated documentation, so I'm closing this ticket.

Also, I'm going to create a separate flag for if-then-else that lets you set cuddling independent of formatting - the sub {} and if {} don't always go hand-in-hand, although I'll probably default to what the outer brace setting is.

I'll make that my next feature to add, I think, so I can get back into the habit of looking at the code. Hopefully going to need to do more of that in the near future anyway.

**Comment by remorse** [comment]
Thanks!
